Traceback (most recent call last):
  File "train_partseg.py", line 352, in <module>
    train(args, io)
  File "train_partseg.py", line 124, in train
    seg_pred = model(data, label_one_hot)
  File "/home/zht/anaconda3/envs/py38torch19/lib/python3.8/site-packages/torch/nn/modules/module.py", line 1051, in _call_impl
    return forward_call(*input, **kwargs)
  File "/home/zht/github_play/crosspoint/CrossPoint/models/dgcnn.py", line 268, in forward
    x0 = get_graph_feature(x, k=self.k)     # (batch_size, 3, num_points) -> (batch_size, 3*2, num_points, k)
  File "/home/zht/github_play/crosspoint/CrossPoint/models/dgcnn.py", line 31, in get_graph_feature
    idx = idx + idx_base
RuntimeError: Expected all tensors to be on the same device, but found at least two devices, cuda:1 and cuda:0!